version: '3.8'

services:
  nimble-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "31415:3000"
    container_name: nimble-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true 